[package]
name = "metriken-archive"
version = "0.4.0"
edition = "2021"
authors = [
    "Brian Martin <brian@iop.systems>",
]
license = "MIT OR Apache-2.0"
description = "Moved to metriken-storage; this crate re-exports it"
homepage = "https://github.com/iopsystems/metriken"
repository = "https://github.com/iopsystems/metriken"

[dependencies]
metriken-storage = { version = "0.1.0", path = "../metriken-storage", default-features = false, features = ["lz4"] }

[features]
write = ["metriken-storage/write"]
stream = ["metriken-storage/stream"]
