[package]
name = "metriken-exposition"
version = "0.1.1"
edition = "2021"
authors = [
    "Brian Martin <brian@iop.systems>",
    "Sean Lynch <sean@iop.systems>",
]
license = "MIT OR Apache-2.0"
description = "Exposition for metriken metrics"
homepage = "https://github.com/iopsystems/metriken"
repository = "https://github.com/iopsystems/metriken"

[dependencies]
chrono = "0.4.34"
histogram = "0.9.1"
metriken = { version = "0.5.1", path = "../metriken" }
rmp-serde = { version = "1.1.2", optional = true }
serde = { version = "1.0.196", features = ["derive"], optional = true }
serde_json = { version = "1.0.114", optional = true }

[features]
serde = ["dep:serde", "chrono/serde", "histogram/serde"]
json = ["dep:serde", "dep:serde_json"]
msgpack = ["dep:serde", "dep:rmp-serde"]
